### ISSUE TITLE
Can't open output file

### ISSUE THREAD

**Issue by Siecje** [jamesabel/osnap#4]
Hey I'm trying to build an installer for this code. 

https://github.com/Siecje/qml-testing/tree/osnap

Full steps are in the [README.md](https://github.com/Siecje/qml-testing/blob/f4345db1c4fa4a9d02654de0e2519ab245948314/README.md) of the repo

``` shell
(osnap) C:\Users\cody\Desktop\qml-testing>python build.py
clearing and making dist (C:\Users\cody\Desktop\qml-testing\dist)
done making dist (C:\Users\cody\Desktop\qml-testing\dist)
unzipping C:\Users\cody\Desktop\osnap\Scripts\..\osnap\launchwin.zip to dist
copying app to dist\osnapp\app
copying osnapy to dist\osnapp\osnapy
copying main.py to dist\osnapp
moving dist\launch.exe to dist\app.exe
writing app.nsis
['c:\\Program Files (x86)\\NSIS\\makensis', 'app.nsis']
Processing config: c:\Program Files (x86)\NSIS\nsisconf.nsh
Processing script file: "app.nsis" (ACP)
warning: LicenseData: empty license file "LICENSE"
 (app.nsis:18)
warning: unknown variable/constant "{INSTALLSIZE}" detected, ignoring (app.nsis:76)

Processed 1 file, writing output (x86-ansi):

Output: "C:\Users\cody\Desktop\qml-testing\installers\app_installer.exe"
Can't open output file
Error - aborting creation process
Traceback (most recent call last):
  File "build.py", line 12, in <module>
    make_installer(True)
  File "build.py", line 9, in make_installer
    [APPLICATION_NAME], '1.0.0', verbose=verbose)
  File "C:\Users\cody\Desktop\osnap\lib\site-packages\osnap\installer.py", line 148, in make_installer
    subprocess.check_call(pkgproj_command)
  File "C:\Users\cody\Anaconda3\lib\subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['c:\\Program Files (x86)\\NSIS\\makensis', 'app.nsis']' returned non-zero exit status 1
```

**Comment by jamesabel** [comment]
It looks like I need to make the 'installers' directory.  It was probably already created manually on my machines.  I'll add code to do this. Thanks!

**Comment by jamesabel** [comment]
Make dir added in 0.0.4.
