### ISSUE TITLE
Version IndexError

### ISSUE THREAD

**Issue by Siecje** [jamesabel/osnap#5]
The code and build steps can be found here https://github.com/Siecje/qml-testing/tree/osnap

When I run build.py I get the following error.

```

(osnap) C:\Users\cody\qml-testing>python build.py
removing dist (C:\Users\cody\qml-testing\dist)
making dist (C:\Users\cody\qml-testing\dist)
removing installers (C:\Users\cody\qml-testing\installers)
making installers (C:\Users\cody\qml-testing\installers)
unzipping c:\users\cody\osnap\lib\site-packages\osnap\launchwin.zip to dist
copying main.py to dist\osnapp
moving dist\launch.exe to dist\app.exe
Traceback (most recent call last):
  File "build.py", line 12, in <module>
    make_installer(True)
  File "build.py", line 9, in make_installer
    [APPLICATION_NAME], '1.0.0', verbose=verbose)
  File "C:\Users\cody\osnap\lib\site-packages\osnap\installer.py", line 21, in make_installer
    installer.make_installer()
  File "C:\Users\cody\osnap\lib\site-packages\osnap\installer_win.py", line 58, in make_installer
    nsis_defines['VERSIONMINOR'] = v[1]
IndexError: list index out of range
```

**Comment by jamesabel** [comment]
I think the problem is that I changed the parameters to make_installer from the original version for overall consistency.  It's now:

def make_installer(python_version, application_name, author='', description='', url='', compile_code=True, verbose=False, use_pyrun=False)

Could you retry with the parameters as above?  Thanks!  BTW I changed the test_example to reflect this.

**Comment by Siecje** [comment]
Thanks that worked!
