### ISSUE TITLE
OSNAP not compatible with the version of windows I'm running

### ISSUE THREAD

**Issue by EliRibble** [jamesabel/osnap#6]
I'm running windows 10 on a VM on a mac.

It's 32-bit on an x86-based processor.

I ran

python -m osnap.osnapy

using python 3.5.2 I get the following:

Z:\temp>python -m osnap.osnapy
get https://www.python.org/ftp/python/3.5.2/python-3.5.2-embed-amd64.zip to cache\python-3.5.2-embed-amd64.zip
Traceback (most recent call last):
  File "C:\Users\Eli Ribble\AppData\Local\Programs\Python\Python35-32\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Eli Ribble\AppData\Local\Programs\Python\Python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Eli Ribble\AppData\Local\Programs\Python\Python35-32\lib\site-packages\osnap\osnapy.py", line 54, in <module>
    main()
  File "C:\Users\Eli Ribble\AppData\Local\Programs\Python\Python35-32\lib\site-packages\osnap\osnapy.py", line 51, in main
    make_osnapy(args.python_version, args.application, args.clear, args.verbose, args.egenix_pyrun, args.force_uninstall)
  File "C:\Users\Eli Ribble\AppData\Local\Programs\Python\Python35-32\lib\site-packages\osnap\osnapy.py", line 30, in make_osnapy
    osnapy.create_python()
  File "C:\Users\Eli Ribble\AppData\Local\Programs\Python\Python35-32\lib\site-packages\osnap\osnapy_win.py", line 58, in create_python
    subprocess.check_call(cmd)
  File "C:\Users\Eli Ribble\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 576, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\Eli Ribble\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Eli Ribble\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Eli Ribble\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
OSError: [WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher

Z:\temp>

**Comment by EliRibble** [comment]
Looks like this related to the get-pip.py. I'm looking in to it more

**Comment by EliRibble** [comment]
Alright, not specifically get-pip.py. It's the python interpreter installed at osnapy/python.exe at the point that we need to run get-pip that has the issue

**Comment by EliRibble** [comment]
Ah, looks like the code may have amd64 hard-coded rather than detecting the OS architecture
